[next-intl] Reading request configuration from ./src/i18n.ts is deprecated, please see https://next-intl.dev/blog/next-intl-3-22#i18n-request — you can either move your configuration to ./i18n/request.ts or provide a custom path in your Next.js config:
const withNextIntl = createNextIntlPlugin(
  './path/to/i18n/request.tsx'
);

 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data

The `locale` parameter in `getRequestConfig` is deprecated, please switch to `await requestLocale`. See https://next-intl.dev/blog/next-intl-3-22#await-request-locale

Error occurred prerendering page "/en/about". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `setRequestLocale` API to enable static rendering, see https://next-intl.dev/docs/getting-started/app-router/with-i18n-routing#static-rendering
    at /home/user/studio/.next/server/chunks/202.js:5:49928
    at /home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:57:3905
    at get locale [as locale] (/home/user/studio/.next/server/chunks/202.js:5:51309)
    at /home/user/studio/.next/server/chunks/951.js:1:2776
    at /home/user/studio/.next/server/chunks/202.js:5:51370
    at /home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:57:3905
    at /home/user/studio/.next/server/chunks/202.js:5:52142
    at /home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:57:3905
    at /home/user/studio/.next/server/chunks/202.js:5:52316
    at /home/user/studio/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:57:3905
Export encountered an error on /[locale]/about/page: /en/about, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null